### ISSUE TITLE
Feature: User can view a list of available jobs

### ISSUE THREAD

**Issue by kyle-kettler** [kyle-kettler/job-board#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view a list of available jobs.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user goes to the home page a list of all available jobs with pagination. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![home](https://github.com/kyle-kettler/job-board/assets/126023512/a816fc04-2320-476f-8083-f73525305396)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to create tables for jobs, users, saved, and applied
- [x] Update `data.sql` to populate some initial data
- [x] Format SQL in `data.sql` to use markdown in the "description" column. 

### ☁️ Server Tasks

- [x] Update `server.ts` to GET jobs from the database and return them ~~in a paginated list.~~ *Because there will only 20-30 items returned, I am going to do frontend pagination and just request all the rows from db.*
- [x] ~~Create pagination middleware to use in GET request.~~
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Install new CRA with TS
- [x] Setup Tailwind CSS
- [x] Create a component for the job cards.
- [x] Create a component for the job list.
- [x] Create a component for card tags.
- [ ] ~~Create a component for buttons~~
- [x] Create a component for the filter form
- [x] Create a navbar component
- [x] Create a footer component
- [x] ~~Install react-paginate and connect to pages from the database~~ Create pagination component
- [x] Build out a static version of the page
- [x] Determine and add needed state variables.
- [x] Determine and add needed events. 
- [x] Write functions to handle events. 
- [x] Add tailwind classes for styles. 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
