### ISSUE TITLE
Feature: User can filter available jobs by location, salary, and experience level.

### ISSUE THREAD

**Issue by kyle-kettler** [kyle-kettler/job-board#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

 Adding filtering capabilities to the FilterForm component

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user enters something into the search field or selects an option with the dropdowns the job list will be filtered

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![home](https://github.com/kyle-kettler/job-board/assets/126023512/d421a817-0ecd-4bb2-96d7-d26fb51f8a98)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `data.sql` to add more jobs to the database

### ⚡ Client Tasks

- [x] Update FilterForm component to filter jobs list based on search term.
- [x] Update FilterForm component to filter jobs list based on location dropdown
- [x] Update FilterForm component to filter jobs list based on level dropdown
- [x] Update FilterForm component to filter jobs list based on salary dropdown
- [x] Make the "clear" button clear the search field
- [x] ~~Add a debounce to the filter so it updates the list after 300ms or so~~ Not needed it only effects the search and the data is not big enough to need it. 
- [x] Add 'Satoshi" font to tailwind config file
- [x] Update all fonts to be 'Satoshi'
- [x] Update favicon
- [x] Update meta data

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
