### ISSUE TITLE
Feature: User can read the entire job description. 

### ISSUE THREAD

**Issue by kyle-kettler** [kyle-kettler/job-board#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Job Details](https://github.com/kyle-kettler/job-board/assets/126023512/ec9bbe2f-48a0-45e8-8779-32c33166615b)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Add more jobs to `data.sql`

### ☁️ Server Tasks

- [x] Update `server.js` with an endpoint for a single row using the jobId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create the job description page.
- [x] Fetch data from server endpoint
- [x] Create a component for JobData.
- [x] Make the JobData card sticky on scroll.
- [x] Learn how to use react-markdown to render the markdown from the db.
- [x] Set styling for the markdown elements.
- [x] Update nav to new design.
- [x] Create button component.

### 🧑‍⚕️ Clean Up Tasks

- [ ] 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
